Telegram agent. Draft.
fetchai/uAgents pull request #175
Opened 2023-10-01 08:08 UTC by ekzarov

2024-07-21 07:49 UTC, Autonomousweb3Dev commented
@jrriehl @ejfitzgerald @cmaliwal can we get review on this PR?

Raised the PR on oct 1 2023 and today is 21 july 2024, it's been almost 9 months.
PR from community shouldn't wait that long for review.

2024-07-23 13:51 UTC, devjsc commented
Sorry for a delay in review, generally we won't review something with "Draft" in the title @Autonomousweb3Dev. I've updated the title now, and I will look to review this later today.

2024-07-23 14:08 UTC, devjsc requested changes

2024-07-23 14:10 UTC, devjsc commented
Please add a project.json file, you will be able to see an example of this here: https://github.com/fetchai/uAgents/blob/main/integrations/gemini_AI_integration/project.json

2024-07-30 05:37 UTC, Autonomousweb3Dev approved these changes

2024-10-07 12:13 UTC, merged