feat: readiness probe
fetchai/uAgents pull request #194
Opened 2023-10-23 16:49 UTC by jrriehl

Implements readiness probe proposed here: https://github.com/fetchai/uAgents/discussions/183.

2023-10-24 16:01 UTC, Archento requested changes
The response setup for the agentverse looks good and the tests are appropriate. I did find an occasion during manual testing though and I am unsure on how detailed the if-else branches should be (we can't catch every case)
So once the two questions are resolved it's green from my side!

2023-10-25 09:29 UTC, jrriehl commented on python/src/uagents/asgi.py
> +            await self.handle_missing_content_type(headers, send)
Fixed, good catch!

2023-10-25 12:43 UTC, ejfitzgerald commented on python/src/uagents/config.py
> +RESPONSE_TIME_HINT_SECONDS = 5
I think this is a reasonable default for the hint response time. I guess from my side the intention here is that this hint value is just a indication (nothing more) about the liveness of the agent. In more IoT scenarios this hint could be much longer.  I guess we should use this a rough hint as to what timeout value we should have for waiting for a response.

2023-10-25 12:59 UTC, Archento approved these changes
I'm good with the current state 👍🏻

2023-10-25 13:19 UTC, merged