chore(integration): remove duplicate agents
fetchai/uAgents pull request #569
Opened 2024-10-23 10:33 UTC by Archento

## Proposed Changes

Removing the first couple of agents that have made it to the new examples repo.

## Types of changes

- [ ] Bug fix (non-breaking change that fixes an issue).
- [ ] New feature added (non-breaking change that adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to stop working as expected).
- [ ] Documentation update.
- [x] Something else (e.g., tests, scripts, example, deployment, infrastructure).

2024-10-23 11:23 UTC, 5A11 approved these changes

2024-10-23 16:09 UTC, jrriehl approved these changes

2024-11-04 15:12 UTC, devjsc requested changes

2024-11-04 15:12 UTC, devjsc commented on integrations/finbert/README.md
Hello, if you remove project.json we will not see this integrations on fetch.ai/integrations

2024-11-04 15:13 UTC, devjsc commented on integrations/finbert/README.md
Where are the agents moved to?

2025-02-04 09:10 UTC, 5A11 approved these changes

2025-02-04 09:28 UTC, devjsc approved these changes

2025-02-04 09:28 UTC, merged