feat(core): Introducing uagents-core
fetchai/uAgents pull request #597
Opened 2024-12-23 16:48 UTC by qati

## Proposed Changes

_[describe the changes here...]_

## Linked Issues

_[if applicable, add links to issues resolved by this PR]_

## Types of changes

_What type of change does this pull request make (put an `x` in the boxes that apply)?_

- [ ] Bug fix (non-breaking change that fixes an issue).
- [ ] New feature added (non-breaking change that adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to stop working as expected).
- [ ] Documentation update.
- [ ] Something else (e.g., tests, scripts, example, deployment, infrastructure).

## Checklist

_Put an `x` in the boxes that apply:_

- [ ] I have read the [CONTRIBUTING](https://github.com/fetchai/uAgents/blob/main/CONTRIBUTING.md) guide
- [ ] Checks and tests pass locally

### If applicable

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added/updated the documentation (executed the script in `python/scripts/generate_api_docs.py`)

## Further comments

_[if this is a relatively large or complex change, kick off a discussion by explaining why you chose the solution you did, what alternatives you considered, etc...]_

2025-01-08 16:39 UTC, jrriehl commented on libs/core/uagents_core/config.py
> +DEFAULT_MAILBOX_API_PATH = "/v1/agents"
Mailbox API includes several other paths as well. Maybe something like this would be more specific?
```suggestion
DEFAULT_REGISTRATION_PATH = "/v1/agents"
```

2025-01-08 16:46 UTC, jrriehl commented on libs/core/uagents_core/logger.py
I guess this is only used in utils, so maybe should be moved there?

2025-01-08 16:49 UTC, jrriehl commented on libs/core/uagents_core/utils/registration.py
> +    agent_address: str
This will likely need an update very soon based on this PR: https://github.com/fetchai/uAgents/pull/603.

2025-01-08 16:51 UTC, jrriehl commented on libs/core/uagents_core/utils/registration.py
> +):
Can we at least use the same API that we use in the async version of this: https://github.com/fetchai/uAgents/blob/main/python/src/uagents/mailbox.py#L87-L92?

2025-01-08 16:54 UTC, jrriehl commented on libs/core/uagents_core/utils/communication.py
> +):
I don't mind having a duplicate sync version of this function, but I'd suggest we use the same or at least very similar naming conventions and API as the async version: https://github.com/fetchai/uAgents/blob/main/python/src/uagents/communication.py#L267-L275

2025-01-08 16:58 UTC, jrriehl commented on libs/core/uagents_core/utils/communication.py
> +    """
Please use Google style docstrings as we do in the rest of the main library:
```
"""
Description

Args:
   arg (type): description

Returns:
    type: description
"""
```

2025-01-08 16:59 UTC, jrriehl commented on libs/core/uagents_core/utils/registration.py
> +    """
Please use Google style docstrings.

2025-01-08 17:02 UTC, jrriehl commented on libs/core/uagents_core/utils/communication.py
> +def lookup_endpoint_for_agent(agent_address: str, *, agentverse_url: Optional[str] = None) -> str:
This is a simplified version of the resolver, which does not handle multiple endpoints, for example. Not sure whether it makes sense to include here.

2025-01-08 17:04 UTC, jrriehl reviewed
Looks good overall. My main comments are about the utilities. Also this should probably go under `python/libs`, right?

2025-01-08 19:48 UTC, qati commented on libs/core/uagents_core/logger.py
I wanted to introduce unified logging and log style to be adopted in the future.

2025-01-08 19:49 UTC, qati commented on libs/core/uagents_core/utils/communication.py
> +def lookup_endpoint_for_agent(agent_address: str, *, agentverse_url: Optional[str] = None) -> str:
first version is fine as it is I guess, but follow up versions needs to improve and add support for multiple endpoints.

2025-01-09 10:40 UTC, Archento requested changes
Since there is a lot of copied/moved code it is actually quite hard to identify what you've changed or added. Also there is no description added to the PR so I can't really understand the reasoning for adding this library.

What is the main benefit for this structure compared to importing what you need for a project directly from uagents?

2025-01-09 10:40 UTC, Archento commented on libs/core/pyproject.toml
> +black = "^24.10.0"
black is not used in this project and the lib right now does not have any tests so please remove all unneeded packages if this is meant to have its own pyproject file.

2025-01-09 10:40 UTC, Archento commented on .github/CODEOWNERS
> +* @jrriehl @Archento @lrahmani @qati
```suggestion
* @jrriehl @Archento @lrahmani

/libs/core/ @qati
```

I propose this scope as your PR only targets changes in this directory.

2025-01-09 10:40 UTC, Archento commented on libs/core/README.md
Please add a description here even if it is preliminary to understand the reasoning behind this package / its reason for existence.

2025-01-09 10:40 UTC, Archento commented on libs/core/pyproject.toml
> +description = "Lightweight framework for rapid agent-based development"
Please check all fields in this file as this seems to be a copy-paste error.

2025-01-14 11:11 UTC, jrriehl commented on libs/core/uagents_core/utils/registration.py
> +        return
For mailbox and proxy agents, we should probably use the standard fixed endpoints: https://github.com/fetchai/uAgents/blob/main/python/src/uagents/config.py#L106-L109.

2025-01-15 12:31 UTC, jrriehl commented on libs/core/pyproject.toml
> +black = "^24.10.0"
Some additional context is that we use `ruff` with pre-commit hooks in the main project and it works very well for us. Maybe worth considering adopting here as well.

2025-01-23 12:40 UTC, merged